# On Apple Silicon, you may need this:

# CONDA_SUBDIR=osx-64 conda env create -n puppy -f PUPpy_environment.yml
# conda activate puppy
# conda env config vars set CONDA_SUBDIR=osx-64

# The only package that wasn't native on Apple Silicon was:
# https://anaconda.org/bioconda/mmseqs2
# It only has linux-64 and osx-64 builds, not osx-arm64.
# Compare to:
# https://anaconda.org/conda-forge/biopython

name: PUPpy
channels:
  - bioconda
  - conda-forge
  - r
  # If I didn't put this at the end, the conda solve was slow:
  # See: https://stackoverflow.com/a/68019710
  - defaults
dependencies:
  - python >=3.10.6
  - mmseqs2 >=v14.7e284
  - pandas >=1.5
  - biopython >=1.80
  - dask >=0.15.2
  - r-tidyverse >=1.3.1
  - r-readr >=2.1.3
  - r-stringi >=1.7.8
  - colorama >=0.4.1
  - pyyaml>=6.0
  # Thad: I added these two:
  - pytest
  - pip

  - pip:
    - primer3-py>=0.6.1

# TODO: Do you need to check this in?  Looks specific to your environment.
# prefix: /project/st-ctropini-1/hghezzi/miniconda3/envs/PUPpy
