package:
  name: puppy
  version: "1.0_beta"

source:
  url: https://github.com/Tropini-lab/PUPpy/archive/refs/tags/v1.0-beta.tar.gz
  sha256: 7679ab2fec988c54b8bee77f230aff8fa0543e77f0dab934f595315596c4d44d

build:
  number: 0

requirements:
  host:
    - python=3.10.6
  run:
    - python >=3.10.6
    - mmseqs2 >=14.7
    - pandas >=1.5
    - biopython >=1.80
    - dask >=0.15.2
    - colorama >=0.4.1
    - primer3-py >=0.6.1
    - seaborn >=0.13.0
    - matplotlib >=3.8.2


test:
  commands:
    - puppy-align -h
    - puppy-primers -h
    - puppy-GUI

about:
  home: https://github.com/Tropini-lab/PUPpy
  license: GPL3
  license_file: LICENSE.txt
  summary: PUPpy a primer design pipeline for substrain-level microbial detection and absolute quantification.


extra:
  recipe-maintainers:
    - hghezzi
