package:
  name: puppy
  version: '1.0.0'

source:
  git_url: https://github.com/Tropini-lab/PUPpy.git

requirements:
  build:
    - python >=3.10.6
    - mmseqs2 >=v14.7e284
    - pandas >=1.5
    - biopython >=1.80
    - dask >=0.15.2
    - r-tidyverse >=1.3.1
    - r-readr >=2.1.3
    - r-stringi >=1.7.8
    - colorama >=0.4.1
    - primer3-py >=0.6.1

  run:
    - python >=3.10.6
    - mmseqs2 >=v14.7e284
    - pandas >=1.5
    - biopython >=1.80
    - dask >=0.15.2
    - r-tidyverse >=1.3.1
    - r-readr >=2.1.3
    - r-stringi >=1.7.8
    - colorama >=0.4.1
    - primer3-py >=0.6.1

build:
  noarch: generic

test:
  commands:
    - puppy-align -h
    - puppy-primers -h

about:
  home:  https://github.com/Tropini-lab/PUPpy
  license: GPLv3
  license_file: ../LICENSE
  summary: PUPpy is a Phylogenetically Unique Primer pipeline in PYthon for high resolution classification of defined microbial communities.
  dev_url: https://github.com/Tropini-lab/PUPpy
  doc_url: https://github.com/Tropini-lab/PUPpy
  doc_source_url: https://github.com/Tropini-lab/PUPpy/blob/main/README.md
  recipe-maintainers:
      - hghezzi
